[workspace]
members = [
    "core",
    "datatypes",
    "examples/basic",
    "examples/basic_dispatching",
    "examples/concurrent_conns",
    "examples/bytes_over_time",
    "examples/enc_conns",
    "examples/encrypted_bytes",
    "examples/measuring_sec",
    "examples/ml_qos",
    "examples/open_vpn",
    "examples/combined",
    "examples/websites",
    "examples/unidentified_conns",
    "tests/functionality/basic_test",
    "tests/functionality/basic_streaming",
    "tests/functionality/basic_tracked", "tests/functionality/weird_combos", "tests/functionality/filter_test",
]
resolver = "2"

[profile.release]
lto = true

[patch.crates-io]
pcap = { git = 'https://github.com/thegwan/pcap', branch = 'compile-optimized' }

